[[Libbpf]]
arch = "aarch64"
git-tree-sha1 = "b5fbe4d1daa0cde9769ffd8615d53266d6aed404"
libc = "glibc"
os = "linux"

    [[Libbpf.download]]
    sha256 = "653f255c15b2ae962aae6102cb4513c41db3fbf4343ba5dbcc1b6d196679866a"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.aarch64-linux-gnu.tar.gz"
[[Libbpf]]
arch = "aarch64"
git-tree-sha1 = "07e519ff1800b7b8119e127055a60223de5d3b45"
libc = "musl"
os = "linux"

    [[Libbpf.download]]
    sha256 = "c224c9bd23d924a46a6b88c387bffbefab043aaba3281489f009e5b5d0fa9571"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.aarch64-linux-musl.tar.gz"
[[Libbpf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c22e0b3893ce44c1049457eeae6f97ea0d388712"
libc = "glibc"
os = "linux"

    [[Libbpf.download]]
    sha256 = "30adc4eb1930f303fd261ce77a35501cd4e7c49589a98661e82caa88a5f421d5"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Libbpf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a26af4ccc4bdf6ec06628b7aabe713a65500f9ab"
libc = "musl"
os = "linux"

    [[Libbpf.download]]
    sha256 = "01c727d0641e564bca45d6702c4b919e889efb1974be33e140d97224d976e97b"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[Libbpf]]
arch = "i686"
git-tree-sha1 = "d8acbc93eec53bf464be739e5bddf23bb6f47b27"
libc = "glibc"
os = "linux"

    [[Libbpf.download]]
    sha256 = "ce103dd98acc56bc0278a60d2ff288c3d821b102ffb6179a09f55a0d9832326b"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.i686-linux-gnu.tar.gz"
[[Libbpf]]
arch = "i686"
git-tree-sha1 = "34d64ad815e44c753e063de872936ea44906465a"
libc = "musl"
os = "linux"

    [[Libbpf.download]]
    sha256 = "7a8a130b47a5d26e3db71496425de85909c4e77bae0c3ce51d00b9e4801af45d"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.i686-linux-musl.tar.gz"
[[Libbpf]]
arch = "powerpc64le"
git-tree-sha1 = "57a43949da77413172a37b70c7fc7805684c9ed0"
libc = "glibc"
os = "linux"

    [[Libbpf.download]]
    sha256 = "0b511754315d3d64caeddb7ce64b0e232cbd0cd5ee4da735218185e4542ad229"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[Libbpf]]
arch = "x86_64"
git-tree-sha1 = "0008de371a272537dd3f50d3cc652dca3c73fd20"
libc = "glibc"
os = "linux"

    [[Libbpf.download]]
    sha256 = "abb435ce1a521a9648514a3429142f4ef57f98572ae726f8dfce088b004e6e7d"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.x86_64-linux-gnu.tar.gz"
[[Libbpf]]
arch = "x86_64"
git-tree-sha1 = "c9db58addf5a20bf7f6eed37ef0856b92311eda4"
libc = "musl"
os = "linux"

    [[Libbpf.download]]
    sha256 = "ce264f9caa99ae61b62c7a33c0ce6b3596696255c78fa4c1a746b804ac1bc5c9"
    url = "https://github.com/JuliaBinaryWrappers/Libbpf_jll.jl/releases/download/Libbpf-v0.5.0+0/Libbpf.v0.5.0.x86_64-linux-musl.tar.gz"
