# Autogenerated wrapper script for Libbpf_jll for armv7l-linux-gnueabihf
export libbpf

using Elfutils_jll
JLLWrappers.@generate_wrapper_header("Libbpf")
JLLWrappers.@declare_library_product(libbpf, "libbpf.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Elfutils_jll)
    JLLWrappers.@init_library_product(
        libbpf,
        "lib/libbpf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
